Add tests for exam-part1
alexnigma/exam-part1 pull request #1
Opened 2023-06-30 16:12 UTC by alexnigma

2023-06-30 20:58 UTC, DmytroSanitarskyi requested changes

2023-06-30 20:58 UTC, DmytroSanitarskyi commented on cypress/e2e/feedback.cy.js
> +            function captchaResult() {
Жах)) ми ж коли if-else розбирали, то домовились, що більше 3 блоків не робимо)) якщо тест потребує більше умов, то використовуємо switch-case, а в цьому випадку взагалі найбільш швидкий, але не ідельний спосіб це використати .eval()

2023-06-30 20:58 UTC, DmytroSanitarskyi commented on cypress/support/helpers/findProduct.js
> +            if (body.find(`[alt*="${productName}"]`).length) {
body.find(`[alt*="${productName}"]`).length > 0

2023-07-02 12:35 UTC, alexnigma commented on cypress/e2e/feedback.cy.js
> +            function captchaResult() {
Fixed)

2023-07-02 12:35 UTC, alexnigma commented on cypress/support/helpers/findProduct.js
> +            if (body.find(`[alt*="${productName}"]`).length) {
fixed)

2023-07-02 12:55 UTC, DmytroSanitarskyi approved these changes

2023-07-03 07:10 UTC, merged